#!/bin/python3 --
#
# This file provides convenience imports for default python shell
#
# echo "export PYTHONSTARTUP=<path/to/this>python3rc" >> ~/.bashrc or ~/.profile 

# Standard packages
import os
import sys
import time
import datetime
import numpy as np

# Auto completion
import rlcompleter, readline
readline.parse_and_bind('tab:complete')

# Add path to the iminspect package
if 'IMINSPECT_ROOT_DIR' in os.environ:
    sys.path.append(os.environ['IMINSPECT_ROOT_DIR'])
else:
    sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from iminspect.inspector import inspect as inspect
